[package]
name = "offf-annotate"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "offf-annotate"
path = "src/main.rs"

[dependencies]
offf-core = { path = "../offf-core" }
clap = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
